### ISSUE TITLE
Crashes with Java 15

### ISSUE THREAD

**Issue by K0-RR** [FalsehoodMC/Fabrication#16]
crash report - https://hatebin.com/msbapjwlke
latest.log - https://hatebin.com/mftbkarvie

**Comment by exaskye** [comment]
This probably has to do with Java 15, not the Fabric version.

**Comment by exaskye** [comment]
(Workaround for now: Disable general.taggable_players)

**Comment by K0-RR** [comment]
Well I don't know how to disable general.taggable_players but I used Fabric Zero mod and it worked. Can you fix it to work with Java 15 or this workaround is the only possibility?

**Comment by exaskye** [comment]
I'll fix it soon, but in general I'd recommend you use the latest Java LTS rather than bleeding. Fabrication works fine on 8 and 11. It seems Oracle broke a (very old) reflection trick that allows you to modify final fields in 15 and I'll probably have to use an access widener instead of this trick.

**Comment by exaskye** [comment]
You can disable general.taggable_players in fabrication.ini.

```ini
[general]
; >>snip<<
; Allows players to be tagged by ops with /fabrication tag.
; Recommended to leave enabled unless there's an extremely unlikely
; incompatibility with another mod.
taggable_players=true
```
