### ISSUE TITLE
Fabric: Launch Crash with Thallium

### ISSUE THREAD

**Issue by IdrisQe** [FalsehoodMC/Fabrication#167]
Fabrication 1.3.3, Thallium 1.10, Minecraft 1.16.5
Thallium PlayerEntityMixin error in relation to particles added by Fabrication, it seems?

https://gist.github.com/IdrisQe/5f2dae88dc86ad88ebb11c8f8448fef0

**Comment by exaskye** [comment]
`[15:38:51] [main/INFO]: Instancing error handler class com.unascribed.fabrication.support.MixinErrorHandler`

This line is because Fabrication has an error handler class it uses for its own mixins. This obnoxious line is a requirement of Mixin. I'll need to add a hack to remove it.

Fabrication has nothing to do with this crash. This is between Zoob and Thallium. Fabrication does not touch any particle code.

**Comment by IdrisQe** [comment]
Oh, sorry! I just saw Fabrication and figured it was some incompatability between the two!
