### ISSUE TITLE
Startup Errors

### ISSUE THREAD

**Issue by srnyx** [FalsehoodMC/Fabrication#181]
I'm not really sure what this is, and I can't really test it with only Fabrication cause it's on my server.
Errors: https://pastebin.com/rY7fw2jU

Full log: https://pastebin.com/BzZ5snjv

**Comment by exaskye** [comment]
Next thing that's gonna happen is someone's going to report a bug to me because Fabrication shows up in the "Loading mods" list.

I don't see a crash, and if there is one, Fabrication is not responsible for it. What you've sent is mandatory warnings printed by Mixin due to how I'm injecting new functionality to allow failsoft mixins.

I've quelled or made obvious all of them but this one now, and at this point I am never going to be rid of these frivolous reports.

**Comment by srnyx** [comment]
> Next thing that's gonna happen is someone's going to report a bug to me because Fabrication shows up in the "Loading mods" list.
> 
> I don't see a crash, and if there is one, Fabrication is not responsible for it. What you've sent is mandatory warnings printed by Mixin due to how I'm injecting new functionality to allow failsoft mixins.
> 
> I've quelled or made obvious all of them but this one now, and at this point I am never going to be rid of these frivolous reports.

Sorry, I don't understand mixin and all that other stuff, so I just report errors/warnings I see in-case they mean anything.
