### ISSUE TITLE
Sodium Overwrite incompatibility

### ISSUE THREAD

**Issue by Zano1999** [FalsehoodMC/Fabrication#30]
Here the crash report:

https://pastebin.com/skGa1A31

**Comment by exaskye** [comment]
Could you please also send your log? It's possible the real error is earlier in the log and this crash report is an aftereffect.

**Comment by exaskye** [comment]
I notice you have an *extremely* outdated version of Java; 8 Update 51. The current version of Oracle Java 8 is Update *271*, and the current version of AdoptOpenJDK Java 8 is Update 275.

It may not be related to this bug, but I strongly recommend you update. 8 Update 51 is from 2015. Also, 1.14+ versions of Minecraft will work on Java 11, which is the current recommended version of Java and is what Fabrication targets.

**Comment by Zano1999** [comment]
Here the latest log:

https://pastebin.com/g7vB67cH

**Comment by exaskye** [comment]
Ah. This is because Fabrication applies an AccessWidener to a method that Sodium patches.

You can fix this by modifying the Sodium jar; add this to its sodium.mixins.json after "plugin":

```json
"overwrites": {
  "conformVisibility": true
},
```

I'm still not entirely sure what should be done about this, whether it's something I should try to fix in Fabrication or something that needs fixing in Sodium.

**Comment by Zano1999** [comment]
Thanks, now it works 😄🐦
