### ISSUE TITLE
Feature order cycle found? - Crash with the 1.18.2 Exp3 Version

### ISSUE THREAD

**Issue by tajemniktv** [FalsehoodMC/Fabrication#446]
Hi,
so I'm using the Fabric 1.18.2, exp 3 version of Fabrication. I loaded a few chunks BEFORE enabling some options in the config (features.ini below) and now, whenever I try to move to a specific place, the game crashes. Tbh I can't tell whether the place was already generated or not. As you can see, I'm using plenty mods so it might be an incompatibility with one of them or with a datapack (if that's even possible). Removing Fabrication mod stopped the crashes. 

**Logs:** https://gist.github.com/tajemniktv/2cbe0316fa9f6c762162885aefdbf1e4
**Features:** https://gist.github.com/tajemniktv/3afc1170ded0c39c67ac9f6fa03204e7
**Datapacks:** https://imgur.com/a/IcGmQoC

_Have a wonderful day_

**Comment by SFort** [comment]
adding `encroaching_emeralds` was a mistake
(near certain it's that since it's the only thing that changes wordgen)
try turning that feature on or off see if that fixes it for now

**Comment by tajemniktv** [comment]
Thank you for such a quick answer. I can confirm that it works just fine after disabling this feature

**Comment by SFort** [comment]
since this doesn't appear to actually happen (in dev env)
my assumption of this being a version update again, was wrong and it's probably a conflict.
since i don't wanna download all those mods to test i'm just gonna guess what went wrong
please test it with [fabrication-i446](https://github.com/SFort/Fabrication/releases/download/v2.3.0/fabrication-1.18.2-2.3.1-i446.jar) (if you prefer compiling the [branch](https://github.com/SFort/Fabrication/tree/446))
or find the conflicting mod in the probable case my guess was wrong

**Comment by tajemniktv** [comment]
I think it works just fine, I'm gonna use it for a bit longer on my main to see if anything happens but I already walked like a thousand or so blocks (newly generated) and not a single crash. So I'm guessing your guess was right :) 
Thank you again and if you need anything more (logs or smth) feel free to hmu!
