### ISSUE TITLE
(Optional) Void Particles are Affected by Distance Effects

### ISSUE THREAD

**Issue by StereoMadnessss** [FalsehoodMC/Fabrication#483]
At high distances like they used to, void particles are still affected by distance effects in Fabrication.

16777216 (both axis)
![2022-06-17_21 49 15](https://user-images.githubusercontent.com/77188051/174423235-272e1241-e21c-4046-a497-02fbfe2e907b.png)

16777216 (x axis)
![2022-06-17_21 50 28](https://user-images.githubusercontent.com/77188051/174423264-e19d0ca6-5eb0-441f-8d1f-d24bf19b3c4e.png)

This is purely **optional** and I do not expect this to get fixed.

**Comment by exaskye** [comment]
The modern particle engine is not susceptible to this problem; it could be simulated, but I don't really feel like it's worth it.

**Comment by SFort** [comment]
I have no idea what i'm looking at

**Comment by exaskye** [comment]
Due to floating point inaccuracy in the old particle system that used 32-bit floats, at high X/Z values the void particles (and all other particles) would group up in pillars at floating point values.

(This can therefore in theory be reproduced just by casting the particle's positions to `float` before rendering.)

**Comment by SFort** [comment]
neat,
unless someone deeply wants this bug i also don't really wanna add it.
(if i did i'd prefer it a seperate setting, that might just bring back the bug compleatly? dunno)

**Comment by SFort** [comment]
i misunderstood, this bug is currently in the feature as the feature was accuratly ported, you'd like the bug fixed not added.
