### ISSUE TITLE
Why not keep updating Forgery?

### ISSUE THREAD

**Issue by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [FalsehoodMC/Fabrication#520]
I **apologize** for posting this question in the wrong place but I couldn't open the other two pages for discussion and suggestions.

**This is undoubtedly a very good project！**But why not keep such a good project up to date at Forgery? Because the version of Forgery is still 2.3.0, which is out of date for Fabrication.

So,plz!Let Forgery get the same treatment as Fabrication, okay?

**Comment by exaskye** [comment]
ForgeryTools stopped working in 1.17 due to bugs in Forge's mixin, and changes to the way mappings are handled in 1.18 broke it completely. I do not personally use Forge and have no real interest in developing for it, especially considering the Forge devs' takes on large collections of vanilla patches such as this.

There have been experiments in getting the newer codebase to work under Forge, but nothing stable enough to release.
