### ISSUE TITLE
Could you update Forgery's version 1.16.5 to version 3.0.3?

### ISSUE THREAD

**Issue by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [FalsehoodMC/Fabrication#552]
**Because you said before**：ForgeryTools stopped working in 1.17 due to bugs in Forge's mixin, and changes to the way mappings are handled in 1.18 broke it completely. I do not personally use Forge and have no real interest in developing for it, especially considering that community's take on large collections of vanilla patches such as this.There have been experiments in getting the newer codebase to work under Forge, but nothing stable enough to release.
So I think Forgery will never be updated again. As a result, you updated it again, which is really great! Now that Forgery version 1.18 has the latest version of the mod, I wonder whether version 1.16 can also have the same version of the mod as version 1.18? If you can do that, I will be very grateful to you!

**Comment by exaskye** [comment]
3.x is currently 1.18+ only, even on Fabric. We've been discussing a 1.16 backport. No promises — this is already a lot of codebases and tooling to maintain.

**Comment by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [comment]
I think I was understand what your mean. Thank you very much for your efforts to update Forgery!

**Comment by SFort** [comment]
i would like to have forgery and fabrication exist on 1.16-1.19+ and all be easily synced to be on the same version / feature set.

for new versions that come after 1.19 the main problem is that the mod has nearing 300 features and any of them could cause a fatal crash (especially true for forgery), they all have to be tested *twice* (forgery/fabrication)
(if this was a smaller mod it would probably also be tested on minor versions)
testing them once takes hours.
then those bugs have to be fixed.
the approach for forgery 3 has been to just disable the ones that crash / void items.
i have no clue what's wrong with most of the features that are currently removed on forgery 3

fabrication 3 mostly uses it's own remapper
(because mixins remapper is hard to hook into, and also compat for other mods implementing their own soft-fail)

the remapper currently sometimes fails.
forgery needs to remap the remapper again which sometimes fails.

the redirect fixer depends on the yarn mappings making it incompatible with forge.
meaning forgery loses one of the compatability benefits of fabrication 3

this and more makes forgery 3 *very* experimental
it's a mess that runs but needs to be fixed

as for 1.16
merging 3.0 to 1.16 is a large amount of effort.
also the 3.0/1.17 branch has issues which need to be resolved before 1.16 can be started.

also neither of us actually use forge, we also both have other projects

**Comment by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [comment]
> 我希望在1.16-1.19 +上存在伪造和制造，并且都可以轻松同步以在同一版本/功能集上。
> 
> 对于1.19之后的新版本，主要问题是该mod具有近300个功能，其中任何一个都可能导致致命的崩溃（特别是对于伪造），它们都必须测试_两次_（伪造/制造）（如果这是一个较小的mod，它可能也会在次要版本上进行测试）测试它们一次需要几个小时。那么这些错误必须得到修复。伪造3的方法是禁用那些崩溃/无效的物品。我不知道目前在伪造3上删除的大多数功能有什么问题
> 
> 制造3主要使用自己的重新映射器（因为mixins重新映射器很难挂接，而且它不会阻止其他mod实现自己的软失败）
> 
> 重新映射器当前有时会失败。伪造需要再次重新映射重新映射器，但有时会失败。
> 
> 重定向固定器依赖于纱线映射，使其与锻造不兼容。这意味着伪造失去了制造的兼容性优势之一 3
> 
> 这个和更多使伪造3_非常_实验性，这是一团糟，运行但需要修复
> 
> 至于1.16合并3.0到1.16是一个很大的努力。此外，3.0/1.17 分支存在需要在启动 1.16 之前解决的问题。
> 
> 我们俩也没有真正使用锻造

It turns out that your work on Forgery is so varied and complicated. I can really understand your feelings. It is true that this great mod is too difficult for Forge to transplant and update. But don't worry. Take your time. Forgery will always be the same as Fabrication!
Please allow me to thank you again, because this is really a great mod! Thank you for your time and effort to improve them！

**Comment by SFort** [comment]
[3.0/1.16](https://github.com/unascribed/fabrication/tree/3.0/1.16) in case you wanna test it

**Comment by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [comment]
> [3.0/1.16](https://github.com/unascribed/fabrication/tree/3.0/1.16)，以防你想测试它

This is fantastic! And it works without any bugs! **Thank you very much** for your efforts to update version 1.16.5!
