### ISSUE TITLE
"Inanimates Can be Invisible Fix" fails to initialise on 1.18.2 Forge

### ISSUE THREAD

**Issue by ghost** [FalsehoodMC/Fabrication#559]
Attached are:
•  Latest.log
•  Debug.log
•  Configuration file

[fabrication.zip](https://github.com/unascribed/Fabrication/files/9845744/fabrication.zip)
[debug.log](https://github.com/unascribed/Fabrication/files/9845745/debug.log)
[latest.log](https://github.com/unascribed/Fabrication/files/9845746/latest.log)

**Comment by SFort** [comment]
[MixinConfigPlugin#58](https://github.com/unascribed/Fabrication/blob/3.0/1.18/src/main/java/com/unascribed/fabrication/support/MixinConfigPlugin.java#L56)
these features are currently force disabled on forgery because atm nobody wants to figure out why they crash.
a few more features get automaticly disabled by forgery.
(assuming the issue is reporting that the feature doesn't work, not that the game crashed)

**Comment by ghost** [comment]
Yeah, reporting that they don't work.  Just posted about it in the Discord and was told to create an issue, I understand if it won't get fixed.  Only reported because it's one of my favourite features.

**Comment by SFort** [comment]
iirc this feature fail is caused by reflection (because of #57)
(could be imagining it tho, i don't remember for sure what causes it)
