### ISSUE TITLE
add feature to disable swiming up flowing water

### ISSUE THREAD

**Issue by Aceplante** [FalsehoodMC/Fabrication#587]
First of all I wanted to thank you and say your mod is AMAZING. It has so many awesome features.

But there is one feature I want desperately but the only mod I can find that does it hasn't been updated since 1.16. Personally, I do not think players should be able to swim up waterfalls/flowing water and I know you said you were not taking any more requests but I think this would fit really well into your mod along with all it's other tweaks. According to the mod page linked below, it only takes (quote) "3 lines of code in the middle of the vanilla method Entity.updateFluidHeightAndDoFluidPushing", but I have no clue how to mod...

The original project can be found here: https://www.curseforge.com/minecraft/mc-mods/you-cannot-swim-up-waterfalls

**Comment by SFort** [comment]
will see when i get around to it, if it's simple enough then sure. (first glance it should be simple)
(the original mod just replaces a vanilla method which fabrication isn't supposed to do for compatability reasons).

**Comment by Aceplante** [comment]
If its optional then there wouldn't be any compatibility issues unless it is manually enabled right?

**Comment by SFort** [comment]
fabrication by default, performs all injections regardless of settings.
and then enables/disables them in order to allow changing them ingame without having to reboot it.
it can told to filter injections using `limit_runtime_configs`. 
(generally if your settings aren't changing i recommend using `limit_runtime_configs` (note that joining a server that uses a feature with a client-side helper counts as the config changing, as does using the world settings feature))
adding a feature that replaces a vanilla method is very much a problem most of the time (especially since the injection happens regardless by default).
making a diffrent injection that does the same thing but without the compat issues isn't really a problem anyhow..

fabrication doing things that cause incopatability is a lot more of an issue then a mod with a single feature doing it.
since most users aren't even using the feature causing the issue.

**Comment by SFort** [comment]
<details> <summary>i just realized you're probably using forgery and this comment doesn't apply</summary> 
just in case you ware thinking fabrication doesn't have enough configs and you'd like to add conditions
 
https://user-images.githubusercontent.com/1879846/219772618-43336df9-6437-49fa-b1e2-d16a92cbaedd.mp4

</details>

**Comment by SFort** [comment]
fabrications variant is going to sink you a lot faster, because at the speed of the linked mod you can still easily swim up a water fall by entering the swiming stance and holding space

**Comment by Aceplante** [comment]
Yes I use forge, was that change applied to forge too or only the fabric version? Either way thank you ill test it out now

**Comment by Aceplante** [comment]
I dont seem to see it, all assume you added it to the fabric version instead?

**Comment by SFort** [comment]
it'll be on the 3.2.0 release when it's released.
the fabric and forge versions are practicly the same jar just ran through a translator of sorts

the only things that are not in the forge release are 
the scripting (shown in the video), 
a few features like launching pistons where forge strugles,
and some techincal bits like the redirect fixer, 
all of these could techincly work on forge just no one has put in the dev effort yet

so for the most part they have exactly the same features.

you can compile the mod yourself if you want it before it's released.
but you'll have to compile [forgeryTools](https://git.sleeping.town/unascribed/ForgeryTools) aswell.
(the translator that turns the fabric jar into the forge one)

probably much easier just to wait

**Comment by Aceplante** [comment]
yes that's okay i can wait I just saw this was supposedly updated but it wasnt showing yet
