### ISSUE TITLE
Forgery 3.2.1 crash with Nostalgic Tweaks 2.0.0-Beta-8.2

### ISSUE THREAD

**Issue by Thombias** [FalsehoodMC/Fabrication#594]
Hi there, i recently updated to forgery-3.2.1+1.18.jar and it appears to be incompatible with Big Brain [https://www.curseforge.com/minecraft/mc-mods/big-brain](url)
I get this error whenever i try to launch my WIP modpack while Forgery 3.2.1 is installed but reverting back to 3.2.0 works fine:
![image](https://user-images.githubusercontent.com/46842890/227808419-950af7a6-87dd-4fb0-930a-3be9251865db.png)

Here's the log file: 
[latest.log](https://github.com/FalsehoodMC/Fabrication/files/11073226/latest.log)

**Comment by SFort** [comment]
could you please add `-Dmixin.debug.export=true` to the launch args, launch the game and then send `.minecraft/.mixin.out/class/net/minecraft/client/renderer/entity/LivingEntityRenderer.class` which will get generated.

i have a good idea as to what is the cause, but i don't think it's a Big Brain conflict and a mixin export is the best way to find the actuall conflicting mod.

**Comment by Thombias** [comment]
Ah so it wasn't BigBrain but Nostalgic Tweaks instead?

**Comment by SFort** [comment]
yup, no clue why BigBrain got blamed for it but as far as i tested it works fine.

it could of just as easily been any mod though (that redirects a field), i think it might of been possible for this kind of crash to happen on fabrication before 3.2.1? it was just a lot less likely. fixed in the next release
