### ISSUE TITLE
"Fixing" weaponized ender pearls?

### ISSUE THREAD

**Issue by Estrelaura** [FalsehoodMC/Fabrication#597]
This might count as a suggestion, but since it isn't a new feature but a modification to an existing one, i figured it might be worth a shot. Instead of replacing the ender pearl altogether, wouldn't making the weaponized behaviour its own item (an enchanted ender pearl, in this case) be more vanilla friendly? Then give it a recipe, loot source or duplication method and you can have both mechanics. I really like this feature, but it's a bit hard to enjoy it when you have to abandon vanilla ender pearls altogether.

**Comment by SFort** [comment]
did it this way because i've wanted to remove controlled teleportation from vanilla for ages and just so happened to think of a fun thing to replace it with.

regardless adding another option to have it as a seperate thing is a good idea.

generally i don't mind feature requests, it's just unlikely i'll be able to take the time, to add a seperate feature.


best thing is probably to just tack on FScript to weponised_ender_pears,

then you could add a recipe for weponized ender pearls
(maybe datapacks/ some scripting mod (idk how NBT recipies work in modern minecraft)).
and in fabrication set weaponized pears to `~nbt~isWeaponized:int:1` (which would only weaponize pears with that nbt tag)

that would be very quick todo, and probably what i'll do when i get the chance. hope that would work for you

**Comment by SFort** [comment]
might be more / the same amount of work in the end nooo clue (don't know if nbt get's transfered from item to entity), will see i guess

**Comment by SFort** [comment]
it will be possible to have both in the next release.
up to you how you make the pearl available, example in clip. (could also just make it available via anvil rename)
(could also have weponized pears be default and vanilla craftable)

https://user-images.githubusercontent.com/1879846/235370468-118b0b27-9fc2-4e3a-8011-5bd7cbe2ff43.mp4

another potential option `~owner:[!sneaky]]` (teleport when sneaking)
