### ISSUE TITLE
Enhanced Moistness & Riptide interaction

### ISSUE THREAD

**Issue by B4CKU** [FalsehoodMC/Fabrication#598]
I'm not entirely sure if it's an oversight or a design choice on purpose, but Riptide (trident enchantment) doesn't seem to work on wet trident users and requires them to stand in water.

If this is a design choice, would it be possible to introduce this interaction as a new option?
(apologies for the feature request)

**Comment by SFort** [comment]
> I'm not entirely sure if it's an oversight or a design choice on purpose

turns out
neither am i
and neither is una

**Comment by SFort** [comment]
doing this involves some injection jank i don't really want to deal with.

https://user-images.githubusercontent.com/1879846/235538810-a8fa6e1d-00f0-4b18-87b4-97418f0dec45.mp4

it also kinda feels like troll physics,
since i think riptide is supposed to be going through water, and not just being wet.
