### ISSUE TITLE
[1.16.5 Forge] Optifine Shaders causes Classic Block Drops to not render the item entity, and render a "half shadow"

### ISSUE THREAD

**Issue by NighthowlerStudios** [FalsehoodMC/Fabrication#610]
What is strange is how it's affecting block drop normals in how they're projected against the shadow map....  

You already use a solution that utilizes mipmaps but what about the UV's?  You can see the broken version of the item entity's shadow only has one triangle showing, and that's on the bottom of the block.  

Used Complementary Shaders 4.7.1 for this, but I believe the issue also appears in any BSL derived shader really.

normal block drops with `classic_block_drops=banned`
![2023-05-30_18 29 17](https://github.com/FalsehoodMC/Fabrication/assets/82226641/63058344-c75a-4b55-b1e7-062b6da7bcf6)

your block drops with `classic_block_drops=unset`
![2023-05-30_18 36 00](https://github.com/FalsehoodMC/Fabrication/assets/82226641/9ea53d8c-fc97-4ec6-b76a-9599874c3bb8)

your block drops with Optifine Shaders OFF
![2023-05-30_18 38 52](https://github.com/FalsehoodMC/Fabrication/assets/82226641/74cecbd8-f0cd-47d5-9e2a-831bc9dc667e)

**Comment by SFort** [comment]
i think this might basicly be issue 92
and if una couldn't fix it i certanly won't be able to.

**Comment by NighthowlerStudios** [comment]
I notice that issue 92 actually had a completely different artifact result hence the new issue.

una claimed in #92 that you have no way to view the pipeline sources.  this is no longer true.  back in 2021 ish, a user opened up a website hosting optifine source code.  sp614x himself gave us permission to decompile purely for the use of studying the code to fix any bugs related, hence this site is still up to this day.  here is a link to the website.  it is hosted by Magma's devs, so it is backed by secure servers and supported by more than the author Hexeption.

because the sources are available to you now, I would love to see you reopen this issue and make an attempt at fixing it, but I can understand if you simply wish not to, and I will keep the feature disabled.

https://optifinesource.co.uk/

**Comment by SFort** [comment]
while this is deffinatly neat.
the last chatlog i have with una that's not just ""do update, k tnx""
is about optifine being jank that should probably go away.

i don't wanna look into this, mostly because it's relativly minor and i'm certain it'll be a huge timesink
(because i'm not that fammiliar with most of it)
(kindof like spending ages trying to improve end portal parallax and the only result being frustrating everyone involved).

fabrication is fragmented into houndrets of little modules which makes it alot simpler to maintain, but also gives me a pretty good excuse to just not fix this and have it be a unresolved conflict that doesn't really impact most of the mod.

not that i like to have lot's of disfunctional quarks, it's just not feasable to fix most optifine issues for example installing optifine also randomly blurs everything in the config menu. why? i don't intend to find out, because optfifine bugs are a timesink
