### ISSUE TITLE
Several Mixins Errors and Warnings - MC 1.19.2 Forge

### ISSUE THREAD

**Issue by Yourname942** [FalsehoodMC/Fabrication#613]
There are several mixins errors and warnings.

Here is the latest log https://pastebin.com/qqwM3udN

I could not get the debug log, as Minecraft is installed in a different drive, and default location does not reflect this.

**Steps to reproduce:**
1. create a new profile
2. Install Forgery
3. Launch Minecraft
4. Set world to creative
5. set difficulty to hard
6. launch the world
7. exit the world
8. exit Minecraft

MC 1.19.2
Forge 43.2.14
forgery-3.2.7+1.19

**Comment by SFort** [comment]
Forgery is in a perpetual beta. it's staying there because forgery tools isn't getting fixed anytime soon.
feel free to request a specific feature to be fixed on forgery, but in general some features are expected to fail.
if the log of those features failing is what bothers you they can be set to banned or you can use limit_runtime_configs.
