### ISSUE TITLE
1.20 Incompatibility with Better Impaling (A trident mod)

### ISSUE THREAD

**Issue by RiginDev** [FalsehoodMC/Fabrication#617]
https://gist.github.com/RiginDev/e0a1f9094ec0251a9e592d12c2102b79

It's an expected error since Fabrication does mess with trident mechanics like this mod, but if it's possible to fix (this was the weirdest crash log I've ever seen), it would be nice

**Comment by SFort** [comment]
as far as i can tell at a grance that mod does the same thing as `balance.bedrock_impaling` i'm guessing that's what's causing the issue so either set bedrock_impaling to banned for now or if possible use the fabrication feature instead

reason why the crash log is cursed is because i hacked together a injection that does improve compatability for some features but also makes terrible mistakes sometimes, although i thought i'd fixed most of these, i'll take a look at what i missed this time

**Comment by RiginDev** [comment]
Yeah removing better impaling is best since Fabrication does that and more! Thx!
