### ISSUE TITLE
(forge 1.19.2) Stacktrace error with Architectury and Blueprint 

### ISSUE THREAD

**Issue by GodzillaFan13** [FalsehoodMC/Fabrication#626]
https://gnomebot.dev/paste/1135340780328849428
https://gnomebot.dev/paste/1135340779968155749
![Screenshot (977)](https://github.com/FalsehoodMC/Fabrication/assets/112220126/e0439ce8-ea91-46fa-b304-bf2ca577c9fa)

i was having an issue with forgery involving Architectury and Blueprint, where it's breaking a mixin. before finding out via the Architectury discord, i had asked one of my friends, and they said it was a stacktrace error, and to remove the 2 mods and then re apply them, which didn't fix the issue at all.
i am simply reporting this to hopefully get it fixed. 
sorry if this is poorly put together, i'm a bit of a newb to github issue reporting.

**Comment by GodzillaFan13** [comment]
weird, removing it hasn't solved the issue. 
https://gnomebot.dev/paste/1135460456245510164
https://gnomebot.dev/paste/1135460455943508058

**Comment by SFort** [comment]
Sorry github notifications have been spotty lately (didn't get notified).
ye the issue format is fine, there's nothing special about github issues really.

There is a forgery error in there, but it's probably not causing the crash?

In general when reporting bugs it's nice to get your mod list to a minimum, because then i can actually easily install the mods and figure out what's happening, (this isn't really viable with 50+mods).
pretty please gradually remove the mods / re-add them untill you only end up with the ones causing the crash.
i have confirmed that just forgery, architectury and blueprint do not cause it.

**Comment by SFort** [comment]
if you figure out if it's forgery causing the it and which mods cause the incompatability, please re open the issue.
