### ISSUE TITLE
Modrinth Not Updated?

### ISSUE THREAD

**Issue by sylv256** [FalsehoodMC/Fabrication#635]
Why isn't the version on Modrinth updated?

**Comment by SFort** [comment]
Una stopped doing releases, due to being increadibly busy.

Which means i started and i'm just more petty when it comes to minor breakages / incoveniances. (i realize this is rich coming from someone who is supposedly "maintaining" forgery)

Modrinth has design decisions that break slightly fringle browsers, it doesn't let me copy the API key and lot's of buttons are broken.

MCModCN doesn't have and API but just uses a session and i'm not taking the time to manually refresh that every time (also wierd networking probably because china).

have poked una, hopefully a disclaimer get's added or something

**Comment by exaskye** [comment]
I passed SFort a Modrinth API token to a dummy account that has permission to create versions.

Uploading all the 3.3.11 artifacts to Modrinth now.

**Comment by Dekamir** [comment]
Any updates on this? There's nothing about Modrinth in the readme or else.

**Comment by SFort** [comment]
https://modrinth.com/mod/fabrication
it's in the description for modrinth.
this would change if there was another semi-active dev that wanted it published there or if una insisted.
just me though, i really don't want too.

**Comment by Dekamir** [comment]
No problem. I couldn't find the mod because it was hidden in searches.
