### ISSUE TITLE
1.20.2 support?

### ISSUE THREAD

**Issue by ArsiTheFox** [FalsehoodMC/Fabrication#641]
Just asking when 1.20.2 support will be available?

Keep up the AMAZING WORK!!!!

**Comment by SFort** [comment]
i just realized 1.20.2 exists yesterday, so i don't really have a good feeling about how hard a port would be yet.
so far all i've seen are some annoying network changes, if that's all there's to it, it will probably be somewhat quick?
anywhere from today to three weeks is my quess

**Comment by SFort** [comment]
looks like likely today (still got a few things to finnish up)

**Comment by ArsiTheFox** [comment]
Now we just need the 1.20.2 version for Forge xP

**Comment by SFort** [comment]
i'm guessing you mean forge?

**Comment by ArsiTheFox** [comment]
> i'm guessing you mean forge?

Ye, sorry I iz le big dumb

**Comment by ArsiTheFox** [comment]
I mean Forge yes, I may move into Fabric at some point but don't know the difference. I have heard Fabric is a little more optimized but that is it. I need to look into it more and see if i need to switch mod loaders

**Comment by SFort** [comment]
it's easier to work with in part because it's split into the modloader and the API.
modloader being the part that loads mods.
API being the part that actually changes minecraft code to give mod devs simpler acces to it.

forge does this in one swoop and just assumes that it's the only thing allowed to change internal bits. 
so when i do change them it can get messy, since forge mightof compleatly removed the code i'm trying to access
fabricAPI also occasionally does this but it's way more rare.

that's a part of why forgery get's updates way later. 
(the other part being forgery uses forgerytools which have been half broken since 1.17, no one has figured out what broke yet, so i'm just juggling the broken bit's untill then)

**Comment by ArsiTheFox** [comment]
Ok so Fabric basically accesses Minecrafts API and Forge kinda goes around that I would say. I used to code randomshiz in forge but there was sooooo much to do with registering and setting stuff up

**Comment by ArsiTheFox** [comment]
Looks like I may be switching to Fabric in the future
