### ISSUE TITLE
Having an issue with multiple modules not initializing.

### ISSUE THREAD

**Issue by ArsiTheFox** [FalsehoodMC/Fabrication#646]
I run a modpack and try to add in Forgery and get no errors in console but multiple modules fail to initialize. The main one being "Grindstone Disenchanting" in the Mechanics section.
I am not near my pc til Friday so not much info could be givin.
Forge: 1.20.1 (47.2.1)

More info will be given soon

I run the modpack "Create: A Perfect World"

Edit: Got the information from the logs
[latest.log](https://github.com/FalsehoodMC/Fabrication/files/13173678/latest.log)

![image](https://github.com/FalsehoodMC/Fabrication/assets/24835664/f94d0afa-a89e-43ec-9811-bb9e466e7988)

many other modules failed as well

**Comment by SFort** [comment]
Yup, Forgery has barely been chugging along since 1.16, no one knows how to fix it.
currently it's not chugging along at all since 1.20.2 forgery is kaput.
unless magic mappings genie, i barley get the time todo fabrication, sorry

edit: i sometimes do hacky patches for specific features but in general the above applies

**Comment by ArsiTheFox** [comment]
`*~Sad foxxor noises~*`
