### ISSUE TITLE
[1.20.1] Crash with Sinytra connector on 3.4.1 Forgery

### ISSUE THREAD

**Issue by Reshy** [FalsehoodMC/Fabrication#650]
Seems like there's a crash occurring between Forgery 3.4.1 and Sinytra Connector Connector-1.0.0-beta.24+1.20.1.jar.  Downgrading to the older 3.4.0 works fine.

Log:  https://pastebin.com/4uiSLNYE

**Comment by SFort** [comment]
3.4.1 changed nothing todo with the crash...
so i guess, forgery release just broke somehow??
here unzip n try this it's the same version just re-compiled [rebuild.zip](https://github.com/FalsehoodMC/Fabrication/files/13355497/rebuild.zip)

Otherwise please narrow down which mod is causing the conflict to something i can reasonably install.
since forgery 3.4.1 and connector-1.0.0-beta.24 standalone doesn't crash when i install them

**Comment by Reshy** [comment]
The version you gave me seems to be working correctly, not encountering the issue so I'm not sure if it was just the compilation having an issue or if it's an anomalous error.

**Comment by SFort** [comment]
you could temporarily use the released version again to find out

**Comment by SFort** [comment]
Anyhow if it's just a wierd compilation thing i'm just going to release the new version that adds a feature

**Comment by SFort** [comment]
and super duper just in case add a crash handler for the inject that failed
