### ISSUE TITLE
"Source dependant invulnerability frames" breaks weapons that reduce invulnerability

### ISSUE THREAD

**Issue by sinedotwav-e** [FalsehoodMC/Fabrication#662]
Fast weapons no longer work with the "source dependant invulnerability frames" option on.

Steps to reproduce:
1. Have a mod that has a weapon that bypasses the usual 0.5 seconds of invulnerability, I am using dixta's Armory's dagger
2. Open minecraft with the "source dependant invulnerability frames" enabled
3. Enter any world
4. Use your fast weapon twice on any mob, the second hit will miss if timed with the damage cooldown

Using the Better Combat mod makes this more apparent since you can just hold down LMB and a similar effect occurs where every second strike misses. I also used the MmmMmmMmmMmm (Target Dummy) mod to test this. The issue still occurs even without these mods.

**Comment by sinedotwav-e** [comment]
I forgot to mention I'm on the 1.19.2 version

**Comment by SFort** [comment]
I'll take a look when i can, but this probably won't get fixed, you should ask the other dev.

**Comment by sinedotwav-e** [comment]
By the other dev, do you mean unascribed? If you do, how should I contact them?

**Comment by SFort** [comment]
no i mean the dev of the mod you're using that's supposed to shorten invulnerability, so "dixta's Armory"

**Comment by sinedotwav-e** [comment]
the same issue still applies to other mods too, sorry for being unclear

**Comment by SFort** [comment]
you ware perfectly clear. i just doubt there's anything i can do about this issue. especially considering i don't know how the other mods change vanilla behavior. and to be perfectly honest i don't have the time right now to debug something that's closed source, so either way, if this ends up being fixed by fabrication or needs individual fixes / interoprability it's probably a good idea to at least ask the other dev what they think or if their up to share what their doing to skip vanilla invurnarability, so i don't have to spend time figuring it out.

**Comment by sinedotwav-e** [comment]
fair enough, thank you for the responses, ill see if i can find out how they skip invulnerability

**Comment by SFort** [comment]
I recommend asking the dev of dixta's Armory or Better Combat to add a config to use two damage types intechangibly instead of trying to remove invulnerability.
I'd rather not go the API route for fixing this if possible.
