### ISSUE TITLE
Minecraft Logo doesn't show up

### ISSUE THREAD

**Issue by notsonytales** [FalsehoodMC/Fabrication#685]
[Latest log link](https://gist.github.com/notsonytales/0ab9ed51fba5f9e23bd55af3c9f5c538)

hi, installed fabrication on 1.20.1 recently and the logo doesnt show up anymore. in the woina section it says the logo is "not ported", though the files listed in the description of it (config/fabrication/block_logo.png and config/fabrication/block_logo.ini) are there.
![Screenshot 1](https://github.com/FalsehoodMC/Fabrication/assets/94196929/f7499bd5-8a77-4c5f-b8ba-211bfec84627)
![Screenshot 2](https://github.com/FalsehoodMC/Fabrication/assets/94196929/a112d43b-5ba1-4b8f-8a4f-64e6bc0f3a8b)

**Comment by SFort** [comment]
Not ported does mean just that. yes the files are still there. but it should be turned off because it doesn't work.
There's a 30 moneyz bounty for it,  if someone feels like fixing it though. i guess you could add to the bounty if you really wanted too, but i'm not managing finances soo anyone shootin for bounties would be goin on a promise on the internet (which tbf isn't much diffrent from what i'm doing)
