### ISSUE TITLE
old armor scale cannot be disabled?

### ISSUE THREAD

**Issue by Aceplante** [FalsehoodMC/Fabrication#704]
forge 1.18.2

old armor scale with durability cannot be disabled (after having it enabled?). I have set it to false on both client and server, reloaded, restarted the world, and even my game, yet armor still decreases with durability. At first I thought maybe it had permanently altered old armor so we just have to get new armor, yet that also lost protection with durability.

**Comment by SFort** [comment]
tested it and i couldn't get this issue.
if you have limit_runtime_configs on, changing anything will require a restart.
otherwise old armor scale, should update on next re-equp or damage taken.

The only thing i can think of that might be happening is you used world specific settings and forgot?

try running both of these on the server and restarting it.
`/forgery config setWorld *.old_armor_scale false`
`/forgery config set *.old_armor_scale false`

**Comment by Aceplante** [comment]
Ah i didnt do setworld

Edit: that didnt seem to work. I ran both of those commands and then reloaded the world, and the armor still deteriorates even after reequipping and letting myself get hit
I also have limit runtime configs set to false

**Comment by SFort** [comment]
setWorld is a bit of a neiche feature if you've never used it you can just ignore it, i just thought it coulda been the cause.

 just to clear things up are you testing this on a server or in a single player and are you using any other mods? (if you're testing on a server please try in singleplayer and if you're using other mods please try without them)

**Comment by Aceplante** [comment]
single player and yes I have other mods. Are there any known to cause issues like this? I guess I can try

**Comment by SFort** [comment]
Nope nothing known, I'm very confused as to what's happening so i'm really hoping that either something obvious was missed, or that it's somehow a mod conflict. because otherwise the only thing i can think of atm is that you upload the logs after running forgery standalone and i try to replicate the install, maybe try a new world? maybe datapack conflict?? but i'm really running out of ideas

**Comment by Aceplante** [comment]
It happened in a new world, but I have not yet tried a separate instance
![ssss](https://github.com/FalsehoodMC/Fabrication/assets/101857505/579ddd22-be6c-4343-a25b-0bfd7c0f7072)

**Comment by Aceplante** [comment]
ah good news, it was indeed another mod. I had armor curve installed, which does a similar thing so thats why I got it confused with yours. Thank you though!
