### ISSUE TITLE
Will there be an update to version 1.21.x in the near future?

### ISSUE THREAD

**Issue by shenyx110** [FalsehoodMC/Fabrication#733]
Will there be an update to version 1.21.x in the near future?

**Comment by SFort** [comment]
#725 #722 
anwser used to be no, @unilock is doing a pr though #729 so maybe?

**Comment by comradesean** [comment]
Just in case it's true and the dev sees this, I just found out that Forge has apparently gone through some drama and the devs have forked off into a new loader called NeoForge.

**Comment by unilock** [comment]
Hi, I'm unilock, the gal working on porting Fabrication to 1.21.

@comradesean I'm aware of Forge being forked off into NeoForge. I intend to get Fabrication 100% working (or as close to that as possible) before starting work on (Neo)Forgery, which is why I haven't bothered changing the buildscript at all yet.

**Comment by SFort** [comment]
go to #735 for the beta test
