### ISSUE TITLE
1.21 Beta test

### ISSUE THREAD

**Issue by SFort** [FalsehoodMC/Fabrication#735]
If anyone has a bit of time to spare. I'd greatly appriciate some pre release testing, just post any issues here.

Unported features: "Old Armor Scale", "Old Armor", "Block Logo", "Legible Signs", "Fullres Banner Shields", "Canhit"

**Comment by anoomolu** [comment]
Didn't expect this so soon haha, thank you so much unilock and SFort 💜 

Running through some stuff I noticed:

- When dropping into my lightly modded instance, it crashed on startup due to an incompat with Moonrise, which was not that surprising given the latter is still ironing out incompat creases: https://mclo.gs/Z9kgqDQ
- Dragon Egg Trails don't seem to spawn particle trails
- InfiBows or the Crossbow variant do not work

All the other settings I usually use seem to work fine!

**Comment by SFort** [comment]
> Moonrise

might be their issue?

**Comment by SFort** [comment]
[Test release 2](https://github.com/FalsehoodMC/Fabrication/releases/download/b3.5.0-2/fabrication-3.5.0+1.21.jar)
