### ISSUE TITLE
[Performance] Taking so much time when launching

### ISSUE THREAD

**Issue by SettingDust** [FalsehoodMC/Fabrication#736]
Many mods are finding the resources from all the packs. The pack from this mod is finding resources from class loader, which is slow. 

I think the resource pack should filter the path instead of finding all the path input

The picture below recorded events should be more accuracy

![图片](https://github.com/user-attachments/assets/44390638-35e2-4cc6-aa12-31dce2214979)
![图片](https://github.com/user-attachments/assets/bed19df7-fb1f-4a74-977a-50e711b8cd8d)

**Comment by SettingDust** [comment]
To clarify, not all 330s are caused by this mod, it's an inverted tree, the time is consumed by all calls
I'll update this issue with a top down tree after a while

**Comment by SFort** [comment]
sure i'll see if i can look into this before the next release.
Please give me instructions to reproduce and measure it, since you already have a setup.

**Comment by SettingDust** [comment]
My pack is way too large. There are 500+ jars.
https://modrinth.com/mod/more-profiling is the tool that providing events. Need to enable the profiling options in config file
Mods that scanning the packs like moremcmeta,continuity, polytone and geckolib should increase the load.
The event from the image is `Find Resources` https://github.com/SettingDust/MoreProfiling/blob/main/src/main/java/settingdust/moreprofiling/mixin/resourceloadevents/findresources/NamespaceResourceManagerMixin.java

**Comment by SFort** [comment]
tried installing some of the mods mentioned along with your mod.
i didn't have much success getting a 13s runtime (always sub-second). it's probably depended on other mods/settings?
i'd still like todo this at some point, but i doubt i'll get to it without a very clear case where it happens. (at which point it may be easier to just pr, since you appear to know the issue and have it setup)
