### ISSUE TITLE
Why no modrinth

### ISSUE THREAD

**Issue by om3ga6400** [FalsehoodMC/Fabrication#739]
why don't you publish this on modrinth

**Comment by SFort** [comment]
i am tired of modern web design, it's increadibly overcomplicated for something that can be simple and it compleatly looses reliablitiy in the process. (there are other gripes but this is the main one)
cf is no saint in this department still their better, probably since their slower to adopt trends.
if cf breaks their site, sure. or if modrinth fixes their buttons, maybe if they keep them fixed.
untill then gh provides a direct download, with no ads.

**Comment by MylesGit** [comment]
I don't understand what Modrinth UI has to do with uploading this mod on there. Isn't Modrinth's whole reason for popularity is that it's a way better experience and/or being open source? Seems like a pretty big plus over CurseForge.

I just want Fabrication on Modrinth because I don't want to add it to Modpacks via overrides. Hope you can consider this.

**Comment by exaskye** [comment]
Modrinth is extremely generous with pack overrides, unlike Curse.

SFort cannot use the Modrinth site *at all* because it is an extremely heavy "SPA" (Single-Page Application) that assumes the presence of a bunch of features he has turned off. Maintaining this project is already an incredibly large burden (I completely gave up on it *long* before SFort did) even when you don't have to wade through a swamp of Modern Web Design in order to get it done.

I personally like Modrinth, but it's not my responsibility or decision anymore, and this project is such a goddamned disaster to build that CI automation is not really practical. We've been through this multiple times. Your Curse-free alternative is the GitHub repo.

**Comment by om3ga6400** [comment]
> Modrinth is extremely generous with pack overrides, unlike Curse.
> 
> SFort cannot use the Modrinth site *at all* because it is an extremely heavy "SPA" (Single-Page Application) that assumes the presence of a bunch of features he has turned off. Maintaining this project is already an incredibly large burden (I completely gave up on it *long* before SFort did) even when you don't have to wade through a swamp of Modern Web Design in order to get it done.
> 
> I personally like Modrinth, but it's not my responsibility or decision anymore, and this project is such a goddamned disaster to build that CI automation is not really practical. We've been through this multiple times. Your Curse-free alternative is the GitHub repo.

I should learn Java just to re-code this from the ground up

**Comment by exaskye** [comment]
Please do maintain a couple hundred fucking mixins for 11 versions of a game (22 including loaders, not even to mention the lack of NeoForge support on the newest versions) where every update has massive internal breaking changes, where there is nothing at all to help you do these updates and you just have to *know* how to find the changes and what it takes to make the mixins work again.

Do all of that for years with nothing but people insulting you and begging for updates and see how much patience *you* have to deal with the bullshit train.
