### ISSUE TITLE
Incompatibility with Embeddium++

### ISSUE THREAD

**Issue by CraftyZombie** [FalsehoodMC/Fabrication#751]
Minecraft 1.20.1
Forge 47.3.12

Mods List:
Embeddium 0.3.31
Embeddium++ 1.2.13
Forgery 3.5.1

When Forgery is installed with Embeddium++ (https://www.curseforge.com/minecraft/mc-mods/embeddiumplus), several issues occur.

1. The config file of Embeddium++ is ignored and overridden with default values.
2. Trying to apply settings after modifying an Embeddium++ option crashes the game.
3. Nether fog becomes a neon green/yellow hue.
4. Lava becomes entirely transparent when submerged.

Because of the diversity of these issues, there might be more problems, but those are the ones that I discovered.

Crash and Logs: https://gist.github.com/CraftyZombie/2e70019bf67dd41c1575f5670c8f1980
Screenshots: https://imgur.com/a/5UqZvYC

**Comment by CraftyZombie** [comment]
https://github.com/SrRapero720/EmbeddiumPlus/issues/84

**Comment by CraftyZombie** [comment]
Sorry, I didn't consider that my config for Forgery is modified.
https://gist.github.com/CraftyZombie/aaec8a02326b86025b3158acce9f7abb

**Comment by SrRapero720** [comment]
~~Embeddium++ has a very explicit logger about loading config and any of your logs has any log output from Embeddium++, the only reason of why it isn't loading is~~
1. ~~Forgery somehow makes Embeddium++ config spec think "its loaded" when it isn't~~
2. ~~Forgery changed the forge environment dist~~


nvm, seems like is not an isolated issue caused by forgery, someting is causing config not load

**Comment by SFort** [comment]
Please figure out what features specifically are in conflict

**Comment by CraftyZombie** [comment]
Found it. Sorry for the wait.
https://gist.github.com/CraftyZombie/8e6b87a6535e2f9ae1affc68f2d27e75

It's the "No Set Window Position" Experiment.

**Comment by SFort** [comment]
@SrRapero720 
https://github.com/SrRapero720/EmbeddiumPlus/blob/1.20.1/src/main/java/me/srrapero720/embeddiumplus/mixins/impl/borderless/BorderlessWindowMixin.java#L14C1-L14C55

the config is being loaded from an improper place.

load the config from a reasonable place, like game startup.

**Comment by SrRapero720** [comment]
thats not an "improper" place, configuration its completly independant from modloader usages.
That little hack early-loads configuration when any mixin requires it early, because if i await for common setup it causes crashes when its attempted to use config fields.

and no, await for loading to update the config only induces weird window size switching, which its not ideal

**Comment by exaskye** [comment]
SFort is correct, this is not a good place to load your configs — especially in a non-layering injection like a redirect. Use a mixin config plugin to run code before any mixins apply.
